### ISSUE TITLE
WorldEdit - Pocket Edition

### ISSUE THREAD

**Issue by dresnite** [sk89q/Plumeria#4]
Hey! I am a PocketMine (the main server software on Minecraft Pocket Edition written in PHP) plugin developer and I am working in the most powerful WorldEdit for this Minecraft's version. I am looking to be recognized as an official WorldEdit developer, can we talk by [twitter](https://twitter.com/EntirelyQuartz) or another social network? 

Also... I apologize for asking here, I didn't find you anywhere else.

**Comment by sk89q** [comment]
Email http://sk89q.com/contact

**Comment by EntirelyQuartz** [comment]
Did you read my email or just ignored it lol
